#服务器端口
server:
  port: 29091

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/

#服务名称
spring:
  application:
    name: @pom.artifactId@

feign:
    hystrix:
        enabled: true

#解决zuul路由超时
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000


profile:pro